### ISSUE TITLE
Unsure How to Use

### ISSUE THREAD

**Issue by KapuLobo** [alzeric/ult_guit_downloader#1]
Hi, and sorry if this doesn't go here, but I've been trying to figure out how to use this? It seems like a very useful tool but I've never worked with py files before.

**Comment by alzeric** [comment]
You'll need to install Python for whatever OS you're using 

I've built this using Python 3.9.10 https://www.python.org/downloads/ (scroll down to Specific Releases)

During installation it'll ask if you want to install to Windows/System PATH .... Be sure to check yes for easiest use.

Once you've completed you now open a console window or powershell window and change to the directory/folder your script is located in. then type

python ult_guit_downloader.py <URL for the Tab on Ultimate-Guitar>

it'll download the tab and create the new file


Hope that helps

**Comment by KapuLobo** [comment]
Thank you so much for the help! But I tried this and it's like my original attempts: module not found. Here is the error if it helps or if you can help me in anyway :) 
![image](https://user-images.githubusercontent.com/101542533/158293819-d95b9ce4-8956-469a-b290-6228a60b7e08.png)

**Comment by alzeric** [comment]
you need to run

`pip install requests`

or 

`python -m pip install --upgrade requests`

**Comment by KapuLobo** [comment]
I got that updated now and it creates a folder where the script is located but it's empty. Here is the error I get now after running the command: 
![image](https://user-images.githubusercontent.com/101542533/158776416-c823066b-b179-4f8f-b48e-2b7227890acb.png)

Also, I don't have to be a pro member do I?

**Comment by alzeric** [comment]
looks like your cookie file may not be setup correct, DM me on discord and I can quickly help you with your issue.  

one thing to look for in your cookies.txt file is make sure you do not have the cookie surrounded by double quotes. " <-
Also make sure you're using a Premium account... fairly certain this does not work on free accounts.

**Comment by alzeric** [comment]
@KapuLobo - I've setup a helpdesk ticket system and support on our AlzKrak discord server please join us and we can get you sorted in no time.

[Join Us on Discord](https://discord.gg/N6ecRsmE)
